version: '3'
services:
  web:
    environment:
      - RAILS_ENV=production
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - KOTONOHA_DATABASE_PASSWORD=${KOTONOHA_DATABASE_PASSWORD}
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "80:3000"
