FROM ruby:2.6.1
RUN apt-get update -qq && apt-get install -y nodejs 

RUN mkdir /myapp
WORKDIR /myapp
COPY Gemfile /myapp/Gemfile
COPY Gemfile.lock /myapp/Gemfile.lock
RUN bundle install
COPY . /myapp

EXPOSE 3000

ARG RAILS_MASTER_KEY
ENV RAILS_MASTER_KEY ${RAILS_MASTER_KEY}
ENV RAILS_ENV=production
RUN RAILS_ENV=production bundle exec rake assets:precompile

CMD ["rm", "-f", "tmp/pids/server.pid"]
CMD ["rails", "server", "-b", "0.0.0.0"]
