version: 2.0
jobs:
  build:
    machine: true
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Start container
          command: docker-compose up -d

      - run: docker-compose exec web rails db:create
      - run: docker-compose exec web rails db:schema:load

      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"

             docker-compose exec web rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress \
              $TEST_FILES

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

  deploy_prod:
    docker:
      - image: circleci/ruby:2.6.1-node-browsers-legacy
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: get AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y python-pip python-dev
            sudo pip install --upgrade awscli

      - run:
          name: build and push a docker image
          command: |
            eval $(aws ecr get-login --no-include-email --region ap-northeast-1)
            docker build -f Dockerfile-prod -t kotonoha-image .  --build-arg RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
            docker tag kotonoha-image:latest 626452400866.dkr.ecr.ap-northeast-1.amazonaws.com/kotonoha-image:$CIRCLE_SHA1
            docker push 626452400866.dkr.ecr.ap-northeast-1.amazonaws.com/kotonoha-image:$CIRCLE_SHA1
      - run:
          name: deploy to ECR
          command: |
            curl https://raw.githubusercontent.com/silinternational/ecs-deploy/master/ecs-deploy | sudo tee /usr/bin/ecs-deploy
            sudo chmod +x /usr/bin/ecs-deploy
            ecs-deploy --skip-deployments-check -t 300 -r ap-northeast-1 --cluster kotonoha-cluster --service-name kotonoha-service --image 626452400866.dkr.ecr.ap-northeast-1.amazonaws.com/kotonoha-image:$CIRCLE_SHA1
            aws ecs run-task --region ap-northeast-1 --cluster kotonoha-cluster --task-definition kotonoha-task  --overrides file://config/ecs.json

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy_prod:
          requires:
            - build
          filters:
            branches:
              only:
                - master
