version: 2.0
jobs:
  build:
    machine: true
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Start container
          command: docker-compose up -d

      - run: docker-compose exec web rails db:create
      - run: docker-compose exec web rails db:schema:load

      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"

             docker-compose exec web rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress \
              $TEST_FILES

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

  deploy_stage:
    docker:
      - image: cdssnc/aws-cli
    steps:
      - run:
          name: set AWS region
          command: aws configure set region ap-northeast-1
      - run:
          name: deploy to ec2
          command: aws deploy create-deployment --application-name kotonoha --deployment-group-name kotonoha-prod --github-location repository=daichi5/kotonoha,commitId=$CIRCLE_SHA1

  deploy_prod:
    docker:
      - image: cdssnc/aws-cli
    steps:
      - run:
          name: set AWS region
          command: aws configure set region ap-northeast-1
      - run:
          name: deploy to ec2
          command: aws deploy create-deployment --application-name kotonoha --deployment-group-name kotonoha-deploy --github-location repository=daichi5/kotonoha,commitId=$CIRCLE_SHA1

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy_stage:
          requires:
            - build
          filters:
            branches:
              only:
                - staging
      - deploy_prod:
          requires:
            - build
          filters:
            branches:
              only:
                - master
